# Site settings
title: Lara Matyushenko's Blog
header-img: img/home-bg.png
email: larabrightside@gmail.com
copyright_name: laramontana
description: > # this means to ignore newlines until "baseurl:"
  Here I post my thoughts about work and life
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  laramontana
learn_profile: laramontana
email_username: larabrightside@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
